# Required
services:
  app:
    image: todo-list-app:latest
    ports:
      - 8080:80

  api:
    image: todo-list-api:latest
    ports:
      - 5166:5166
    env_file:
      ./api.env

  reports-api:
    image: todo-list-reports-api:latest

  db:
    image: postgres:15.0-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata

