apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-db
spec:
  selector:
    matchLabels:
      app: todo-list-db
  template:
    metadata:
      labels:
        app: todo-list-db
    spec:
      containers:
        - name: todo-list-db
          image: postgres:15.0-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
