apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pg-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-volume-claim
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
