apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - name: app
      image: todo-list-app:latest
      imagePullPolicy: Never
      resources:
        limits:
          memory: "128Mi"
          cpu: 100m
