apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-app
spec:
  selector:
    matchLabels:
      app: todo-list-app
  template:
    metadata:
      labels:
        app: todo-list-app
    spec:
      # volumes:
      #   - name: config-volume
      #     configMap:
      #       name: app-config
      containers:
        - name: todo-list-app
          image: todo-list-app:latest
          imagePullPolicy: Never
          # volumeMounts:
          #   - name: config-volume
          #     mountPath: /usr/share/nginx/html/assets/config.json
          #     subPath: config.json
          resources:
            limits:
              memory: "128Mi"
              cpu: 100m
