apiVersion: v1
kind: Secret
metadata:
  name: connectionstring
type: Opaque
data:
  connstring: SG9zdD10b2RvLWxpc3QtZGI6NTQzMjtVc2VybmFtZT1wb3N0Z3JlcztQYXNzd29yZD1wYXNzd29yZDtEYXRhYmFzZT1wb3N0Z3Jlcw== # Host=todo-list-db:5432;Username=postgres;Password=password;Database=postgres
